#  우분트22 workflow 
name: Deploy to Ubuntu-22 on Push Event

# 작업이 실행되는 시기를 제어합니다. UI를 사용하여 수동으로 트리거되면 워크플로가 실행됩니다.
# or API.
on:
  push:
    branches : ["main"]



# 워크플로 실행은 순차적으로 또는 병렬로 실행될 수 있는 하나 이상의 작업으로 구성됩니다.
jobs:
  # 배포작업  "deploy"
  deploy:
    # 작업이 실행될 실행기 유형
    runs-on: ubuntu-latest   # 작업환경 : Ubuntu 최신버전 18 , 22  등 버전입력 하면 작동 안될수 있음

    # 단계는 작업의 일부로 실행될 일련의 작업을 나타냅니다.
    steps:
    # 배포 셸을 사용하여 단일 명령을 실행합니다.
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.REACT_SERVER_HOST }}
        username: ${{ secrets.REACT_SERVER_USER }}
        password: ${{ secrets.REACT_SERVER_PASSWORD }}
        port: ${{ secrets.REACT_SERVER_PORT }}
      

    - name: Install dependencies and build 
      run: |
            mkdir aaa
            rm -rf jpa-shop-maven-and-gradle-front/
            git clone https://github.com/braverokmc79/jpa-shop-maven-and-gradle-front.git
            cd jpa-shop-maven-and-gradle-front/ 
            npm run install
            npm run build